fangraphs:
  fg_batters:
    url: http://www.fangraphs.com/leaders.aspx?pos=all&stats=bat&lg=all&qual=0&type=c,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,60,61,62,102,103,104,105,106,107,108,109,110,111,206,207,208,209,210,211&season=2018&month=0&season1=2018&ind=0&team=&rost=&age=&filter=&players=
    js_cmd: __doPostBack('LeaderBoard1$cmdCSV','')
    filename: FanGraphs Leaderboard.csv
    columns:
      - name
      - team
      - age
      - g
      - ab
      - pa
      - h
      - one_b
      - two_b
      - three_b
      - hr
      - r
      - rbi
      - bb
      - ibb
      - so
      - hbp
      - sf
      - sh
      - gdp
      - sb
      - cs
      - avg
      - ifh
      - bu
      - buh
      - bb_perc
      - k_perc
      - bb_k
      - obp
      - slg
      - ops
      - iso
      - babip
      - gb_fb
      - ld_perc
      - gb_perc
      - fb_perc
      - iffb_perc
      - hr_fb
      - ifh_perc
      - buh_perc
      - woba
      - wraa
      - wrc
      - spd
      - wrc_plus
      - wpa
      - o_swing_perc
      - z_swing_perc
      - swing_perc
      - o_contact_perc
      - z_contact_perc
      - contact_perc
      - zone_perc
      - f_strike_perc
      - swstr_perc
      - bsr
      - pull_perc
      - cent_perc
      - oppo_perc
      - soft_perc
      - med_perc
      - hard_perc
      - fg_id
  fg_batters_daily:
    url: http://www.fangraphs.com/leaderssplits.aspx?splitArr=&strgroup=game&statgroup=1&startDate=2018-03-01&endDate=2018-11-01&filter=&position=B&statType=player&autoPt=false&sort=22,1&pg=0
    js_cmd: __doPostBack('SplitsLeaderboard$cmdCSV','')
    filename: FanGraphs Splits Leaderboard Data.csv
    columns:
      - game_date
      - name
      - fg_id
      - team
      - g
      - pa
      - ab
      - h
      - one_b
      - two_b
      - three_b
      - hr
      - r
      - rbi
      - bb
      - ibb
      - so
      - hbp
      - sf
      - sh
      - gdp
      - sb
      - cs
      - avg
      - bb_perc
      - k_perc
      - bb_k
      - avg1
      - obp
      - slg
      - ops
      - iso
      - babip
      - w_rc
      - w_raa
      - w_oba
      - wrc_plus
      - gb_fb
      - ld_perc
      - gb_perc
      - fb_perc
      - iffb_perc
      - hr_fb
      - ifh_perc
      - buh_perc
      - pull_perc
      - cent_perc
      - oppo_perc
      - soft_perc
      - med_perc
      - hard_perc
  fg_batters_home:
    url: http://www.fangraphs.com/leaderssplits.aspx?splitArr=7&strgroup=season&statgroup=1&startDate=2018-03-01&endDate=2018-11-01&filter=&position=B&statType=player&autoPt=false&sort=22,1&pg=0
    js_cmd: __doPostBack('SplitsLeaderboard$cmdCSV','')
    filename: FanGraphs Splits Leaderboard Data -- Home.csv
    columns:
      - season
      - name
      - fg_id
      - team
      - g
      - pa
      - ab
      - h
      - one_b
      - two_b
      - three_b
      - hr
      - r
      - rbi
      - bb
      - ibb
      - so
      - hbp
      - sf
      - sh
      - gdp
      - sb
      - cs
      - avg
      - bb_perc
      - k_perc
      - bb_k
      - avg1
      - obp
      - slg
      - ops
      - iso
      - babip
      - w_rc
      - w_raa
      - w_oba
      - wrc_plus
      - gb_fb
      - ld_perc
      - gb_perc
      - fb_perc
      - iffb_perc
      - hr_fb
      - ifh_perc
      - buh_perc
      - pull_perc
      - cent_perc
      - oppo_perc
      - soft_perc
      - med_perc
      - hard_perc
  fg_batters_away:
    url: http://www.fangraphs.com/leaderssplits.aspx?splitArr=8&strgroup=season&statgroup=1&startDate=2018-03-01&endDate=2018-11-01&filter=&position=B&statType=player&autoPt=false&sort=22,1&pg=0
    js_cmd: __doPostBack('SplitsLeaderboard$cmdCSV','')
    filename: FanGraphs Splits Leaderboard Data -- Away.csv
    columns:
      - season
      - name
      - fg_id
      - team
      - g
      - pa
      - ab
      - h
      - one_b
      - two_b
      - three_b
      - hr
      - r
      - rbi
      - bb
      - ibb
      - so
      - hbp
      - sf
      - sh
      - gdp
      - sb
      - cs
      - avg
      - bb_perc
      - k_perc
      - bb_k
      - avg1
      - obp
      - slg
      - ops
      - iso
      - babip
      - w_rc
      - w_raa
      - w_oba
      - wrc_plus
      - gb_fb
      - ld_perc
      - gb_perc
      - fb_perc
      - iffb_perc
      - hr_fb
      - ifh_perc
      - buh_perc
      - pull_perc
      - cent_perc
      - oppo_perc
      - soft_perc
      - med_perc
      - hard_perc
  fg_batters_lhp:
    url: http://www.fangraphs.com/leaderssplits.aspx?splitArr=1&strgroup=season&statgroup=1&startDate=2018-03-01&endDate=2018-11-01&filter=&position=B&statType=player&autoPt=false&sort=22,1&pg=0
    js_cmd: __doPostBack('SplitsLeaderboard$cmdCSV','')
    filename: FanGraphs Splits Leaderboard Data -- vs LHP.csv
    columns:
      - season
      - name
      - fg_id
      - team
      - g
      - pa
      - ab
      - h
      - one_b
      - two_b
      - three_b
      - hr
      - r
      - rbi
      - bb
      - ibb
      - so
      - hbp
      - sf
      - sh
      - gdp
      - sb
      - cs
      - avg
      - bb_perc
      - k_perc
      - bb_k
      - avg1
      - obp
      - slg
      - ops
      - iso
      - babip
      - w_rc
      - w_raa
      - w_oba
      - wrc_plus
      - gb_fb
      - ld_perc
      - gb_perc
      - fb_perc
      - iffb_perc
      - hr_fb
      - ifh_perc
      - buh_perc
      - pull_perc
      - cent_perc
      - oppo_perc
      - soft_perc
      - med_perc
      - hard_perc
  fg_batters_rhp:
    url: http://www.fangraphs.com/leaderssplits.aspx?splitArr=2&strgroup=season&statgroup=1&startDate=2018-03-01&endDate=2018-11-01&filter=&position=B&statType=player&autoPt=false&sort=22,1&pg=0
    js_cmd: __doPostBack('SplitsLeaderboard$cmdCSV','')
    filename: FanGraphs Splits Leaderboard Data -- vs RHP.csv
    columns:
      - season
      - name
      - fg_id
      - team
      - g
      - pa
      - ab
      - h
      - one_b
      - two_b
      - three_b
      - hr
      - r
      - rbi
      - bb
      - ibb
      - so
      - hbp
      - sf
      - sh
      - gdp
      - sb
      - cs
      - avg
      - bb_perc
      - k_perc
      - bb_k
      - avg1
      - obp
      - slg
      - ops
      - iso
      - babip
      - w_rc
      - w_raa
      - w_oba
      - wrc_plus
      - gb_fb
      - ld_perc
      - gb_perc
      - fb_perc
      - iffb_perc
      - hr_fb
      - ifh_perc
      - buh_perc
      - pull_perc
      - cent_perc
      - oppo_perc
      - soft_perc
      - med_perc
      - hard_perc
  fg_pitchers:
    url: http://www.fangraphs.com/leaders.aspx?pos=all&stats=sta&lg=all&qual=0&type=c,47,48,49,50,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,218,219,220,221,222,223&season=2018&month=0&season1=2018&ind=0&team=0&rost=0&age=0&filter=&players=0
    js_cmd: __doPostBack('LeaderBoard1$cmdCSV','')
    filename: FanGraphs Leaderboard.csv
    columns:
      - name
      - team
      - ld_perc
      - gb_perc
      - fb_perc
      - iffb_perc
      - wfb
      - wsl
      - wct
      - wcb
      - wch
      - wsf
      - wkn
      - wfb_c
      - wsl_c
      - wct_c
      - wcb_c
      - wch_c
      - wsf_c
      - wkn_c
      - o_swing_perc
      - z_swing_perc
      - swing_perc
      - o_contact_perc
      - z_contact_perc
      - contact_perc
      - zone_perc
      - f_strike_perc
      - swstr_perc
      - pull_perc
      - cent_perc
      - oppo_perc
      - soft_perc
      - med_perc
      - hard_perc
      - fg_id
  fg_pitchers_daily:
    url: http://www.fangraphs.com/leaderssplits.aspx?splitArr=&strgroup=game&statgroup=1&startDate=2018-03-01&endDate=2018-11-01&filter=&position=P&statType=player&autoPt=true&sort=19,-1&pg=0
    js_cmd: __doPostBack('SplitsLeaderboard$cmdCSV','')
    filename: FanGraphs Splits Leaderboard Data.csv
    columns:
      - game_date
      - name
      - fg_id
      - team
      - ip
      - tbf
      - h
      - two_b
      - three_b
      - r
      - er
      - hr
      - bb
      - ibb
      - hbp
      - so
      - avg
      - obp
      - slg
      - era
      - w_oba
      - k_9
      - bb_9
      - k_bb
      - hr_9
      - k_perc
      - bb_perc
      - k_bb_perc
      - avg1
      - whip
      - babip
      - lob_perc
      - x_fip
      - fip
      - gb_fb
      - ld_perc
      - gb_perc
      - fb_perc
      - iffb_perc
      - hr_fb
      - ifh_perc
      - buh_perc
      - pull_perc
      - cent_perc
      - oppo_perc
      - soft_perc
      - med_perc
      - hard_perc
  fg_pitchers_home:
    url: http://www.fangraphs.com/leaderssplits.aspx?splitArr=9&strgroup=season&statgroup=1&startDate=2018-03-01&endDate=2018-11-01&filter=&position=P&statType=player&autoPt=false&pg=0&sort=19,-1
    js_cmd: __doPostBack('SplitsLeaderboard$cmdCSV','')
    filename: FanGraphs Splits Leaderboard Data -- Home.csv
    columns:
      - season
      - name
      - fg_id
      - team
      - ip
      - tbf
      - h
      - two_b
      - three_b
      - r
      - er
      - hr
      - bb
      - ibb
      - hbp
      - so
      - avg
      - obp
      - slg
      - era
      - w_oba
      - k_9
      - bb_9
      - k_bb
      - hr_9
      - k_perc
      - bb_perc
      - k_bb_perc
      - avg1
      - whip
      - babip
      - lob_perc
      - x_fip
      - fip
      - gb_fb
      - ld_perc
      - gb_perc
      - fb_perc
      - iffb_perc
      - hr_fb
      - ifh_perc
      - buh_perc
      - pull_perc
      - cent_perc
      - oppo_perc
      - soft_perc
      - med_perc
      - hard_perc
  fg_pitchers_away:
    url: http://www.fangraphs.com/leaderssplits.aspx?splitArr=10&strgroup=season&statgroup=1&startDate=2018-03-01&endDate=2018-11-01&filter=&position=P&statType=player&autoPt=false&pg=0&sort=19,-1
    js_cmd: __doPostBack('SplitsLeaderboard$cmdCSV','')
    filename: FanGraphs Splits Leaderboard Data -- Away.csv
    columns:
      - season
      - name
      - fg_id
      - team
      - ip
      - tbf
      - h
      - two_b
      - three_b
      - r
      - er
      - hr
      - bb
      - ibb
      - hbp
      - so
      - avg
      - obp
      - slg
      - era
      - w_oba
      - k_9
      - bb_9
      - k_bb
      - hr_9
      - k_perc
      - bb_perc
      - k_bb_perc
      - avg1
      - whip
      - babip
      - lob_perc
      - x_fip
      - fip
      - gb_fb
      - ld_perc
      - gb_perc
      - fb_perc
      - iffb_perc
      - hr_fb
      - ifh_perc
      - buh_perc
      - pull_perc
      - cent_perc
      - oppo_perc
      - soft_perc
      - med_perc
      - hard_perc
  fg_pitchers_lhb:
    url: http://www.fangraphs.com/leaderssplits.aspx?splitArr=5&strgroup=season&statgroup=1&startDate=2018-03-01&endDate=2018-11-01&filter=&position=P&statType=player&autoPt=false&pg=0&sort=19,-1
    js_cmd: __doPostBack('SplitsLeaderboard$cmdCSV','')
    filename: FanGraphs Splits Leaderboard Data -- vs LHH.csv
    columns:
      - season
      - name
      - fg_id
      - team
      - ip
      - tbf
      - h
      - two_b
      - three_b
      - r
      - er
      - hr
      - bb
      - ibb
      - hbp
      - so
      - avg
      - obp
      - slg
      - era
      - w_oba
      - k_9
      - bb_9
      - k_bb
      - hr_9
      - k_perc
      - bb_perc
      - k_bb_perc
      - avg1
      - whip
      - babip
      - lob_perc
      - x_fip
      - fip
      - gb_fb
      - ld_perc
      - gb_perc
      - fb_perc
      - iffb_perc
      - hr_fb
      - ifh_perc
      - buh_perc
      - pull_perc
      - cent_perc
      - oppo_perc
      - soft_perc
      - med_perc
      - hard_perc
  fg_pitchers_rhb:
    url: http://www.fangraphs.com/leaderssplits.aspx?splitArr=6&strgroup=season&statgroup=1&startDate=2018-03-01&endDate=2018-11-01&filter=&position=P&statType=player&autoPt=false&pg=0&sort=19,-1
    js_cmd: __doPostBack('SplitsLeaderboard$cmdCSV','')
    filename: FanGraphs Splits Leaderboard Data -- vs RHH.csv
    columns:
      - season
      - name
      - fg_id
      - team
      - ip
      - tbf
      - h
      - two_b
      - three_b
      - r
      - er
      - hr
      - bb
      - ibb
      - hbp
      - so
      - avg
      - obp
      - slg
      - era
      - w_oba
      - k_9
      - bb_9
      - k_bb
      - hr_9
      - k_perc
      - bb_perc
      - k_bb_perc
      - avg1
      - whip
      - babip
      - lob_perc
      - x_fip
      - fip
      - gb_fb
      - ld_perc
      - gb_perc
      - fb_perc
      - iffb_perc
      - hr_fb
      - ifh_perc
      - buh_perc
      - pull_perc
      - cent_perc
      - oppo_perc
      - soft_perc
      - med_perc
      - hard_perc
  fg_team_batters_hand_lhp:
    url: http://www.fangraphs.com/leaderssplits.aspx?splitArr=1&strgroup=season&statgroup=1&startDate=2018-03-01&endDate=2018-11-01&filter=&position=B&statType=team&autoPt=false&sort=21,1&pg=0
    js_cmd: __doPostBack('SplitsLeaderboard$cmdCSV','')
    filename: FanGraphs Splits Leaderboard Data -- vs LHP.csv
    columns:
      - season
      - team
      - g
      - pa
      - ab
      - h
      - one_b
      - two_b
      - three_b
      - hr
      - r
      - rbi
      - bb
      - ibb
      - so
      - hbp
      - sf
      - sh
      - gdp
      - sb
      - cs
      - avg
      - bb_perc
      - k_perc
      - bb_k
      - avg1
      - obp
      - slg
      - ops
      - iso
      - babip
      - w_rc
      - w_raa
      - w_oba
      - wrc_plus
      - gb_fb
      - ld_perc
      - gb_perc
      - fb_perc
      - iffb_perc
      - hr_fb
      - ifh_perc
      - buh_perc
      - pull_perc
      - cent_perc
      - oppo_perc
      - soft_perc
      - med_perc
      - hard_perc
  fg_team_batters_hand_rhp:
    url: http://www.fangraphs.com/leaderssplits.aspx?splitArr=2&strgroup=season&statgroup=1&startDate=2018-03-01&endDate=2018-11-01&filter=&position=B&statType=team&autoPt=false&sort=21,1&pg=0
    js_cmd: __doPostBack('SplitsLeaderboard$cmdCSV','')
    filename: FanGraphs Splits Leaderboard Data -- vs RHP.csv
    columns:
      - season
      - team
      - g
      - pa
      - ab
      - h
      - one_b
      - two_b
      - three_b
      - hr
      - r
      - rbi
      - bb
      - ibb
      - so
      - hbp
      - sf
      - sh
      - gdp
      - sb
      - cs
      - avg
      - bb_perc
      - k_perc
      - bb_k
      - avg1
      - obp
      - slg
      - ops
      - iso
      - babip
      - w_rc
      - w_raa
      - w_oba
      - wrc_plus
      - gb_fb
      - ld_perc
      - gb_perc
      - fb_perc
      - iffb_perc
      - hr_fb
      - ifh_perc
      - buh_perc
      - pull_perc
      - cent_perc
      - oppo_perc
      - soft_perc
      - med_perc
      - hard_perc
rotoguru:
  dfs:
    url: http://rotoguru1.com/cgi-bin/mlb-dbd-2018.pl?forcelogin=1&user=%s&key=%s
    columns:
      - guru_id
      - mlb_id
      - name_last_first
      - name_first_last
      - p_h
      - hand
      - game_date
      - team
      - oppt
      - h_a
      - game_num
      - game_id
      - game_time
      - team_score
      - oppt_score
      - home_ump
      - temp
      - w_condition
      - w_speed
      - w_dir
      - adi
      - prior_adi
      - gs
      - gp
      - pos
      - bat_order
      - oppt_pitch_hand
      - oppt_pitch_guru_id
      - oppt_pitch_mlb_id
      - oppt_pitch_name
      - pa
      - woba_num
      - ip
      - w_l_s
      - qs
      - fd_points
      - dk_points
      - dd_points
      - yh_points
      - fd_salary
      - dk_salary
      - dd_salary
      - yh_salary
      - fd_pos
      - dk_pos
      - dd_pos
      - yh_pos
statcast:
  statcast_batters:
    url: https://baseballsavant.mlb.com/statcast_leaderboard?year=2018&abs=0&player_type=resp_batter_id
    columns:
      - name
      - attempts
      - max_hit_speed
      - min_hit_speed
      - avg_hit_speed
      - fbld
      - gb
      - max_distance
      - avg_distance
      - avg_hr_distance
      - mlb_id
      - player_type
      - season
      - resp_batter_id
      - barrels
      - brl_percent
      - brl_pa
      - ev95plus
      - ev95percent
      - rowId
